// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDF0w5o7r_ykPmvmZvL_P3nnxIFJNTqmvU',
    appId: '1:985273512403:web:5d4fb1a3f6b32167aabf26',
    messagingSenderId: '985273512403',
    projectId: 'automatic-feeder-be881',
    authDomain: 'automatic-feeder-be881.firebaseapp.com',
    storageBucket: 'automatic-feeder-be881.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDNrqwrrgyk5a71gEfNXtOlOw2cZtS3OwE',
    appId: '1:985273512403:android:b02493626d9c055aaabf26',
    messagingSenderId: '985273512403',
    projectId: 'automatic-feeder-be881',
    storageBucket: 'automatic-feeder-be881.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAaC5BnIjA1RJDghMaw8Z0NFM7dpXTzRTc',
    appId: '1:985273512403:ios:779598ebafdb6220aabf26',
    messagingSenderId: '985273512403',
    projectId: 'automatic-feeder-be881',
    storageBucket: 'automatic-feeder-be881.firebasestorage.app',
    iosBundleId: 'com.example.automaticFeeder',
  );
}
